<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="icon" type="image/x-icon" href="/images/delivery-truck-3331471_640.png">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <link href="/css/my-style.css" rel="stylesheet">

    <title>Server-Side Programming - <?php echo $view->pageTitle; ?></title>
</head>


<body class="d-flex flex-column h-100">

<!--<body role=""document"> -->


    <header>
        <!-- Fixed navbar -->
        <?php if ($view->showNavbar) { ?>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">

                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="index.php">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="deliveryPoints.php">Delivery Points</a>
                        </li>
                        <!--
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="test.php">Test</a>
                        </li>
                        -->
                    </ul>
                    <!--Search form-->
                    <form name="searchForm" class="d-flex" role="search" action="searchDeliveries.php" method="POST">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search_query">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>

                    <p id="loginName"><?php if(isset($view->result)) {
                        echo $view->result;
                        } ?></p>
                </div>
            </div>
        </nav>
        <?php } ?>
    </header>


    <!-- Begin page content -->
    <main class="flex-shrink-0">

        <div class="container">
            <div  class="row">
                <div id="title" class="col-xs-12">
                    <img src="images/delivery-truck-3331471_640.png" alt="Ismail's Delivery Website" />
                    <img src="images/delivery-truck-3331471_640.png" alt="Ismail's Delivery Website" />
                    <img src="images/delivery-truck-3331471_640.png" alt="Ismail's Delivery Website" />
                    <img src="images/delivery-truck-3331471_640.png" alt="Ismail's Delivery Website" />
                    <img src="images/delivery-truck-3331471_640.png" alt="Ismail's Delivery Website" />
                    <img src="images/delivery-truck-3331471_640.png" alt="Ismail's Delivery Website" />
                    <img src="images/delivery-truck-3331471_640.png" alt="Ismail's Delivery Website" />
                    <img src="images/delivery-truck-3331471_640.png" alt="Ismail's Delivery Website" />
                    <img src="images/delivery-truck-3331471_640.png" alt="Ismail's Delivery Website" />


                    <h1><?php echo $view->pageTitle ?> </h1>

                    <!-- https://getbootstrap.com/docs/5.2/examples/sticky-footer-navbar/ -->

                </div>
            </div>

            <div class="row">
               <section id="content" class="col-xs-6 col-sm-9 col-md-10">



